//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SimuladorUnicoEntities : DbContext
    {
        public SimuladorUnicoEntities()
            : base("name=SimuladorUnicoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Cobertura> Tbl_Cobertura { get; set; }
        public virtual DbSet<Tbl_Grupo_Status> Tbl_Grupo_Status { get; set; }
        public virtual DbSet<Tbl_Produto> Tbl_Produto { get; set; }
        public virtual DbSet<Tbl_Produto_Cobertura> Tbl_Produto_Cobertura { get; set; }
        public virtual DbSet<Tbl_Ramo> Tbl_Ramo { get; set; }
        public virtual DbSet<Tbl_Status> Tbl_Status { get; set; }
        public virtual DbSet<Tbl_Tipo_Cobertura> Tbl_Tipo_Cobertura { get; set; }
        public virtual DbSet<Tbl_Usuario> Tbl_Usuario { get; set; }
    }
}
