//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Usuario
    {
        public Tbl_Usuario()
        {
            this.Tbl_Cobertura = new HashSet<Tbl_Cobertura>();
            this.Tbl_Grupo_Status = new HashSet<Tbl_Grupo_Status>();
            this.Tbl_Produto = new HashSet<Tbl_Produto>();
            this.Tbl_Produto_Cobertura = new HashSet<Tbl_Produto_Cobertura>();
            this.Tbl_Ramo = new HashSet<Tbl_Ramo>();
            this.Tbl_Status = new HashSet<Tbl_Status>();
        }
    
        public int id_usuario { get; set; }
        public string nm_usuario { get; set; }
        public int id_usuario_ex { get; set; }
        public string login { get; set; }
        public string senha { get; set; }
    
        public virtual ICollection<Tbl_Cobertura> Tbl_Cobertura { get; set; }
        public virtual ICollection<Tbl_Grupo_Status> Tbl_Grupo_Status { get; set; }
        public virtual ICollection<Tbl_Produto> Tbl_Produto { get; set; }
        public virtual ICollection<Tbl_Produto_Cobertura> Tbl_Produto_Cobertura { get; set; }
        public virtual ICollection<Tbl_Ramo> Tbl_Ramo { get; set; }
        public virtual ICollection<Tbl_Status> Tbl_Status { get; set; }
    }
}
