//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Tipo_Cobertura
    {
        public Tbl_Tipo_Cobertura()
        {
            this.Tbl_Cobertura = new HashSet<Tbl_Cobertura>();
        }
    
        public int id_tipo_cobertura { get; set; }
        public string nm_tipo_cobertura { get; set; }
    
        public virtual ICollection<Tbl_Cobertura> Tbl_Cobertura { get; set; }
    }
}
