//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Produto_Cobertura
    {
        public int id_cobertura { get; set; }
        public int id_produto { get; set; }
        public Nullable<decimal> limite_resseguro { get; set; }
        public bool dv_ressegurada { get; set; }
        public decimal limite_cobertura { get; set; }
        public int id_usuario { get; set; }
        public System.DateTime dt_cadastro { get; set; }
        public System.DateTime dt_inicio_vigencia { get; set; }
        public Nullable<System.DateTime> dt_fim_vigencia { get; set; }
        public Nullable<decimal> vl_base { get; set; }
        public Nullable<int> id_produto_cobertura_ex { get; set; }
    
        public virtual Tbl_Cobertura Tbl_Cobertura { get; set; }
        public virtual Tbl_Produto Tbl_Produto { get; set; }
        public virtual Tbl_Usuario Tbl_Usuario { get; set; }
    }
}
