//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Status
    {
        public Tbl_Status()
        {
            this.Tbl_Cobertura = new HashSet<Tbl_Cobertura>();
            this.Tbl_Produto = new HashSet<Tbl_Produto>();
            this.Tbl_Ramo = new HashSet<Tbl_Ramo>();
        }
    
        public int id_status { get; set; }
        public string nm_status { get; set; }
        public int id_grp_status { get; set; }
        public bool dv_ativo { get; set; }
        public Nullable<int> id_status_ex { get; set; }
        public int id_usuario { get; set; }
        public System.DateTime dt_cadastro { get; set; }
    
        public virtual ICollection<Tbl_Cobertura> Tbl_Cobertura { get; set; }
        public virtual Tbl_Grupo_Status Tbl_Grupo_Status { get; set; }
        public virtual ICollection<Tbl_Produto> Tbl_Produto { get; set; }
        public virtual ICollection<Tbl_Ramo> Tbl_Ramo { get; set; }
        public virtual Tbl_Usuario Tbl_Usuario { get; set; }
    }
}
