//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ramo
    {
        public Tbl_Ramo()
        {
            this.Tbl_Cobertura = new HashSet<Tbl_Cobertura>();
            this.Tbl_Produto = new HashSet<Tbl_Produto>();
        }
    
        public int id_ramo { get; set; }
        public int nr_ramo { get; set; }
        public string nm_ramo { get; set; }
        public Nullable<int> id_ramo_ext { get; set; }
        public int id_status { get; set; }
        public int id_usuario { get; set; }
        public System.DateTime dt_cadastro { get; set; }
        public string cod_susep { get; set; }
    
        public virtual ICollection<Tbl_Cobertura> Tbl_Cobertura { get; set; }
        public virtual ICollection<Tbl_Produto> Tbl_Produto { get; set; }
        public virtual Tbl_Status Tbl_Status { get; set; }
        public virtual Tbl_Usuario Tbl_Usuario { get; set; }
    }
}
