//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Produto
    {
        public Tbl_Produto()
        {
            this.Tbl_Produto_Cobertura = new HashSet<Tbl_Produto_Cobertura>();
        }
    
        public int id_produto { get; set; }
        public Nullable<int> id_produto_ext { get; set; }
        public string nm_produto { get; set; }
        public int id_status { get; set; }
        public int id_ramo { get; set; }
        public int id_usuario { get; set; }
        public System.DateTime dt_cadastro { get; set; }
    
        public virtual ICollection<Tbl_Produto_Cobertura> Tbl_Produto_Cobertura { get; set; }
        public virtual Tbl_Ramo Tbl_Ramo { get; set; }
        public virtual Tbl_Status Tbl_Status { get; set; }
        public virtual Tbl_Usuario Tbl_Usuario { get; set; }
    }
}
